title: <span style="color:black">Teri Campbell</span> # your name (or website title) here

logo: "/images/Teri_Head_Shot.png?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-informed professional healthcare entrepreneur, problem solver, and avid learner with extensive clinical healthcare experience. 
  <br><br>
  <a href="https://www.linkedin.com/in/teriscampbell/">LinkedIn Profile</a> 
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
